# Server   : localhost
# Port     : 3306
# User     : coworking
# Password : coworking123

services:
  co-working-space:
    image: co-working-space
    build:
      context: ./Co-working-Space
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=CoWorkingSpace;User Id=coworking;Password=coworking123
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=CoWorkingSpace
      - MYSQL_USER=coworking
      - MYSQL_PASSWORD=coworking123
    volumes:
      - mysql-db:/var/lib/mysql
    container_name: mysql
    restart: always

volumes:
  mysql-db:
